### ISSUE TITLE
foreman-proxy does not start after container restart

### ISSUE THREAD

**Issue by matt-cahill** [gbevan/ubuntu-foreman#1]
running `/etc/init.d/foreman-proxy start` inside the container fixes for that run

cheers for putting this together, i'm just starting to play around with docker and this is a great jumping off point.

Matt

**Comment by gbevan** [comment]
Thanks for this Matt.  
I've updated the dockerfile to issue the proxy start now.  I've also bumped the foreman version from 1.7 to 1.10

**Comment by matt-cahill** [comment]
many thanks
